connection_type: udp
udp_listen_port: 14551

drones:
  drone1:
    system_id: 1
    endpoint: "127.0.0.1:14552"
    name: "Pixhawk6C Main"
  drone2:
    system_id: 2
    endpoint: "127.0.0.1:14552"
    name: "Pixhawk6C (sysid=2)"
